version: '3.1'

services:

  db:
    image: postgres:14.8-alpine3.18
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
