spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: pass
  jpa:
    show-sql: true
    #    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
