package com.example.order.model;

import com.example.order.converter.BigDecimalStringConverter;
import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;


@Data
@RequiredArgsConstructor
@Builder
@AllArgsConstructor
@DynamoDbBean
public class Order {
    @Getter(onMethod_ = {@DynamoDbPartitionKey})
    private String id;
    private OrderStatus warehouseStatus;
    private OrderStatus paymentStatus;
    @Getter(onMethod = @__({@DynamoDbSecondaryPartitionKey(indexNames = "userId-index")}))
    private String userId;
    @Getter(onMethod = @__({@DynamoDbConvertedBy(BigDecimalStringConverter.class)}))
    private BigDecimal totalAmount;
    private String shippingAddress;
    @Getter(onMethod = @__({@DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)}))
    private Instant createdDate;
    @Setter(onMethod_ = {@DynamoDbAutoGeneratedTimestampAttribute})
    private Instant lastModifiedDate;
    private List<OrderedProduct> products;
}
