db:
  payment:
    tableName: PaymentAccount
    partitionKey: userId
    sortKey: orderId
  paymentView:
    tableName: PaymentAccountView
    partitionKey: userId

payment:
  postfix:
    deposit: _deposit
    cancel: _cancel
    receipt: _payment

eventResultNotification:
  topicArn: arn:aws:sns:us-east-1:288453301076:EventResultListener.fifo

queue:
  name: Payment.fifo
  waitTimeSeconds: 10
  maxNumberOfMessages: 5

server:
  port : 8081

event:
  source: payment